###+-----------------------------------------------------------------------------------+
###|                                                                                   |
###| Generated by SLEC-2024.1/1088044  (Jan 29 2024)  linux64  S2401292355             |
###| on Fri Apr  5 23:54:58 2024.                                                      |
###|                                                                                   |
###| Restrictions concerning the use of Siemens SLEC                                   |
###| are covered in the license agreement. Distribution to third party                 |
###| is strictly prohibited.                                                           |
###|                                                                                   |
###+-----------------------------------------------------------------------------------+

###----------------------------------------------------------###
###      User specified clock roots                          ###


###----------------------------------------------------------###
###      Inferred clock roots                                ###

####+-----------------------------------------------------------------------------------+
###|                                                                                   |
###| Generated by SLEC-2024.1/1088044  (Jan 29 2024)  linux64  S2401292355             |
###| on Fri Apr  5 23:54:58 2024.                                                      |
###|                                                                                   |
###| Restrictions concerning the use of Siemens SLEC                                   |
###| are covered in the license agreement. Distribution to third party                 |
###| is strictly prohibited.                                                           |
###|                                                                                   |
###+-----------------------------------------------------------------------------------+

###----------------------------------------------------------###
###      User specified clock roots                          ###


###----------------------------------------------------------###
###      Inferred clock roots                                ###

## Clock : _Ideal_Clk_ (Period : 100, Rising edge : 2, Falling edge : 52) is set on spec.clk

###----------------------------------------------------------###
###      Default clock-domain assignments                    ###


###----------------------------------------------------------###
